package eu.darken.capod.common.theming

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

object ThemeColorProvider {

    fun getLightColorScheme(color: ThemeColor, style: ThemeStyle): ColorScheme = when (color) {
        ThemeColor.BLUE -> blueLightScheme(style)
        ThemeColor.GREEN -> greenLightScheme(style)
        ThemeColor.AMBER -> amberLightScheme(style)
    }

    fun getDarkColorScheme(color: ThemeColor, style: ThemeStyle): ColorScheme = when (color) {
        ThemeColor.BLUE -> blueDarkScheme(style)
        ThemeColor.GREEN -> greenDarkScheme(style)
        ThemeColor.AMBER -> amberDarkScheme(style)
    }

    private fun blueLightScheme(style: ThemeStyle): ColorScheme {
        val c = CapodColorsBlue
        return when (style) {
            ThemeStyle.MEDIUM_CONTRAST -> lightColorScheme(
                primary = c.primaryLightMediumContrast,
                onPrimary = c.onPrimaryLightMediumContrast,
                primaryContainer = c.primaryContainerLightMediumContrast,
                onPrimaryContainer = c.onPrimaryContainerLightMediumContrast,
                secondary = c.secondaryLightMediumContrast,
                onSecondary = c.onSecondaryLightMediumContrast,
                secondaryContainer = c.secondaryContainerLightMediumContrast,
                onSecondaryContainer = c.onSecondaryContainerLightMediumContrast,
                tertiary = c.tertiaryLightMediumContrast,
                onTertiary = c.onTertiaryLightMediumContrast,
                tertiaryContainer = c.tertiaryContainerLightMediumContrast,
                onTertiaryContainer = c.onTertiaryContainerLightMediumContrast,
                error = c.errorLightMediumContrast,
                onError = c.onErrorLightMediumContrast,
                errorContainer = c.errorContainerLightMediumContrast,
                onErrorContainer = c.onErrorContainerLightMediumContrast,
                background = c.backgroundLightMediumContrast,
                onBackground = c.onBackgroundLightMediumContrast,
                surface = c.surfaceLightMediumContrast,
                onSurface = c.onSurfaceLightMediumContrast,
                surfaceVariant = c.surfaceVariantLightMediumContrast,
                onSurfaceVariant = c.onSurfaceVariantLightMediumContrast,
                outline = c.outlineLightMediumContrast,
                inverseSurface = c.inverseSurfaceLightMediumContrast,
                inverseOnSurface = c.inverseOnSurfaceLightMediumContrast,
                inversePrimary = c.inversePrimaryLightMediumContrast,
            )
            ThemeStyle.HIGH_CONTRAST -> lightColorScheme(
                primary = c.primaryLightHighContrast,
                onPrimary = c.onPrimaryLightHighContrast,
                primaryContainer = c.primaryContainerLightHighContrast,
                onPrimaryContainer = c.onPrimaryContainerLightHighContrast,
                secondary = c.secondaryLightHighContrast,
                onSecondary = c.onSecondaryLightHighContrast,
                secondaryContainer = c.secondaryContainerLightHighContrast,
                onSecondaryContainer = c.onSecondaryContainerLightHighContrast,
                tertiary = c.tertiaryLightHighContrast,
                onTertiary = c.onTertiaryLightHighContrast,
                tertiaryContainer = c.tertiaryContainerLightHighContrast,
                onTertiaryContainer = c.onTertiaryContainerLightHighContrast,
                error = c.errorLightHighContrast,
                onError = c.onErrorLightHighContrast,
                errorContainer = c.errorContainerLightHighContrast,
                onErrorContainer = c.onErrorContainerLightHighContrast,
                background = c.backgroundLightHighContrast,
                onBackground = c.onBackgroundLightHighContrast,
                surface = c.surfaceLightHighContrast,
                onSurface = c.onSurfaceLightHighContrast,
                surfaceVariant = c.surfaceVariantLightHighContrast,
                onSurfaceVariant = c.onSurfaceVariantLightHighContrast,
                outline = c.outlineLightHighContrast,
                inverseSurface = c.inverseSurfaceLightHighContrast,
                inverseOnSurface = c.inverseOnSurfaceLightHighContrast,
                inversePrimary = c.inversePrimaryLightHighContrast,
            )
            else -> lightColorScheme(
                primary = c.primaryLight,
                onPrimary = c.onPrimaryLight,
                primaryContainer = c.primaryContainerLight,
                onPrimaryContainer = c.onPrimaryContainerLight,
                secondary = c.secondaryLight,
                onSecondary = c.onSecondaryLight,
                secondaryContainer = c.secondaryContainerLight,
                onSecondaryContainer = c.onSecondaryContainerLight,
                tertiary = c.tertiaryLight,
                onTertiary = c.onTertiaryLight,
                tertiaryContainer = c.tertiaryContainerLight,
                onTertiaryContainer = c.onTertiaryContainerLight,
                error = c.errorLight,
                onError = c.onErrorLight,
                errorContainer = c.errorContainerLight,
                onErrorContainer = c.onErrorContainerLight,
                background = c.backgroundLight,
                onBackground = c.onBackgroundLight,
                surface = c.surfaceLight,
                onSurface = c.onSurfaceLight,
                surfaceVariant = c.surfaceVariantLight,
                onSurfaceVariant = c.onSurfaceVariantLight,
                outline = c.outlineLight,
                inverseSurface = c.inverseSurfaceLight,
                inverseOnSurface = c.inverseOnSurfaceLight,
                inversePrimary = c.inversePrimaryLight,
            )
        }
    }

    private fun blueDarkScheme(style: ThemeStyle): ColorScheme {
        val c = CapodColorsBlue
        return when (style) {
            ThemeStyle.MEDIUM_CONTRAST -> darkColorScheme(
                primary = c.primaryDarkMediumContrast,
                onPrimary = c.onPrimaryDarkMediumContrast,
                primaryContainer = c.primaryContainerDarkMediumContrast,
                onPrimaryContainer = c.onPrimaryContainerDarkMediumContrast,
                secondary = c.secondaryDarkMediumContrast,
                onSecondary = c.onSecondaryDarkMediumContrast,
                secondaryContainer = c.secondaryContainerDarkMediumContrast,
                onSecondaryContainer = c.onSecondaryContainerDarkMediumContrast,
                tertiary = c.tertiaryDarkMediumContrast,
                onTertiary = c.onTertiaryDarkMediumContrast,
                tertiaryContainer = c.tertiaryContainerDarkMediumContrast,
                onTertiaryContainer = c.onTertiaryContainerDarkMediumContrast,
                error = c.errorDarkMediumContrast,
                onError = c.onErrorDarkMediumContrast,
                errorContainer = c.errorContainerDarkMediumContrast,
                onErrorContainer = c.onErrorContainerDarkMediumContrast,
                background = c.backgroundDarkMediumContrast,
                onBackground = c.onBackgroundDarkMediumContrast,
                surface = c.surfaceDarkMediumContrast,
                onSurface = c.onSurfaceDarkMediumContrast,
                surfaceVariant = c.surfaceVariantDarkMediumContrast,
                onSurfaceVariant = c.onSurfaceVariantDarkMediumContrast,
                outline = c.outlineDarkMediumContrast,
                inverseSurface = c.inverseSurfaceDarkMediumContrast,
                inverseOnSurface = c.inverseOnSurfaceDarkMediumContrast,
                inversePrimary = c.inversePrimaryDarkMediumContrast,
            )
            ThemeStyle.HIGH_CONTRAST -> darkColorScheme(
                primary = c.primaryDarkHighContrast,
                onPrimary = c.onPrimaryDarkHighContrast,
                primaryContainer = c.primaryContainerDarkHighContrast,
                onPrimaryContainer = c.onPrimaryContainerDarkHighContrast,
                secondary = c.secondaryDarkHighContrast,
                onSecondary = c.onSecondaryDarkHighContrast,
                secondaryContainer = c.secondaryContainerDarkHighContrast,
                onSecondaryContainer = c.onSecondaryContainerDarkHighContrast,
                tertiary = c.tertiaryDarkHighContrast,
                onTertiary = c.onTertiaryDarkHighContrast,
                tertiaryContainer = c.tertiaryContainerDarkHighContrast,
                onTertiaryContainer = c.onTertiaryContainerDarkHighContrast,
                error = c.errorDarkHighContrast,
                onError = c.onErrorDarkHighContrast,
                errorContainer = c.errorContainerDarkHighContrast,
                onErrorContainer = c.onErrorContainerDarkHighContrast,
                background = c.backgroundDarkHighContrast,
                onBackground = c.onBackgroundDarkHighContrast,
                surface = c.surfaceDarkHighContrast,
                onSurface = c.onSurfaceDarkHighContrast,
                surfaceVariant = c.surfaceVariantDarkHighContrast,
                onSurfaceVariant = c.onSurfaceVariantDarkHighContrast,
                outline = c.outlineDarkHighContrast,
                inverseSurface = c.inverseSurfaceDarkHighContrast,
                inverseOnSurface = c.inverseOnSurfaceDarkHighContrast,
                inversePrimary = c.inversePrimaryDarkHighContrast,
            )
            else -> darkColorScheme(
                primary = c.primaryDark,
                onPrimary = c.onPrimaryDark,
                primaryContainer = c.primaryContainerDark,
                onPrimaryContainer = c.onPrimaryContainerDark,
                secondary = c.secondaryDark,
                onSecondary = c.onSecondaryDark,
                secondaryContainer = c.secondaryContainerDark,
                onSecondaryContainer = c.onSecondaryContainerDark,
                tertiary = c.tertiaryDark,
                onTertiary = c.onTertiaryDark,
                tertiaryContainer = c.tertiaryContainerDark,
                onTertiaryContainer = c.onTertiaryContainerDark,
                error = c.errorDark,
                onError = c.onErrorDark,
                errorContainer = c.errorContainerDark,
                onErrorContainer = c.onErrorContainerDark,
                background = c.backgroundDark,
                onBackground = c.onBackgroundDark,
                surface = c.surfaceDark,
                onSurface = c.onSurfaceDark,
                surfaceVariant = c.surfaceVariantDark,
                onSurfaceVariant = c.onSurfaceVariantDark,
                outline = c.outlineDark,
                inverseSurface = c.inverseSurfaceDark,
                inverseOnSurface = c.inverseOnSurfaceDark,
                inversePrimary = c.inversePrimaryDark,
            )
        }
    }

    private fun greenLightScheme(style: ThemeStyle): ColorScheme {
        val c = CapodColorsGreen
        return when (style) {
            ThemeStyle.MEDIUM_CONTRAST -> lightColorScheme(
                primary = c.primaryLightMediumContrast,
                onPrimary = c.onPrimaryLightMediumContrast,
                primaryContainer = c.primaryContainerLightMediumContrast,
                onPrimaryContainer = c.onPrimaryContainerLightMediumContrast,
                secondary = c.secondaryLightMediumContrast,
                onSecondary = c.onSecondaryLightMediumContrast,
                secondaryContainer = c.secondaryContainerLightMediumContrast,
                onSecondaryContainer = c.onSecondaryContainerLightMediumContrast,
                tertiary = c.tertiaryLightMediumContrast,
                onTertiary = c.onTertiaryLightMediumContrast,
                tertiaryContainer = c.tertiaryContainerLightMediumContrast,
                onTertiaryContainer = c.onTertiaryContainerLightMediumContrast,
                error = c.errorLightMediumContrast,
                onError = c.onErrorLightMediumContrast,
                errorContainer = c.errorContainerLightMediumContrast,
                onErrorContainer = c.onErrorContainerLightMediumContrast,
                background = c.backgroundLightMediumContrast,
                onBackground = c.onBackgroundLightMediumContrast,
                surface = c.surfaceLightMediumContrast,
                onSurface = c.onSurfaceLightMediumContrast,
                surfaceVariant = c.surfaceVariantLightMediumContrast,
                onSurfaceVariant = c.onSurfaceVariantLightMediumContrast,
                outline = c.outlineLightMediumContrast,
                inverseSurface = c.inverseSurfaceLightMediumContrast,
                inverseOnSurface = c.inverseOnSurfaceLightMediumContrast,
                inversePrimary = c.inversePrimaryLightMediumContrast,
            )
            ThemeStyle.HIGH_CONTRAST -> lightColorScheme(
                primary = c.primaryLightHighContrast,
                onPrimary = c.onPrimaryLightHighContrast,
                primaryContainer = c.primaryContainerLightHighContrast,
                onPrimaryContainer = c.onPrimaryContainerLightHighContrast,
                secondary = c.secondaryLightHighContrast,
                onSecondary = c.onSecondaryLightHighContrast,
                secondaryContainer = c.secondaryContainerLightHighContrast,
                onSecondaryContainer = c.onSecondaryContainerLightHighContrast,
                tertiary = c.tertiaryLightHighContrast,
                onTertiary = c.onTertiaryLightHighContrast,
                tertiaryContainer = c.tertiaryContainerLightHighContrast,
                onTertiaryContainer = c.onTertiaryContainerLightHighContrast,
                error = c.errorLightHighContrast,
                onError = c.onErrorLightHighContrast,
                errorContainer = c.errorContainerLightHighContrast,
                onErrorContainer = c.onErrorContainerLightHighContrast,
                background = c.backgroundLightHighContrast,
                onBackground = c.onBackgroundLightHighContrast,
                surface = c.surfaceLightHighContrast,
                onSurface = c.onSurfaceLightHighContrast,
                surfaceVariant = c.surfaceVariantLightHighContrast,
                onSurfaceVariant = c.onSurfaceVariantLightHighContrast,
                outline = c.outlineLightHighContrast,
                inverseSurface = c.inverseSurfaceLightHighContrast,
                inverseOnSurface = c.inverseOnSurfaceLightHighContrast,
                inversePrimary = c.inversePrimaryLightHighContrast,
            )
            else -> lightColorScheme(
                primary = c.primaryLight,
                onPrimary = c.onPrimaryLight,
                primaryContainer = c.primaryContainerLight,
                onPrimaryContainer = c.onPrimaryContainerLight,
                secondary = c.secondaryLight,
                onSecondary = c.onSecondaryLight,
                secondaryContainer = c.secondaryContainerLight,
                onSecondaryContainer = c.onSecondaryContainerLight,
                tertiary = c.tertiaryLight,
                onTertiary = c.onTertiaryLight,
                tertiaryContainer = c.tertiaryContainerLight,
                onTertiaryContainer = c.onTertiaryContainerLight,
                error = c.errorLight,
                onError = c.onErrorLight,
                errorContainer = c.errorContainerLight,
                onErrorContainer = c.onErrorContainerLight,
                background = c.backgroundLight,
                onBackground = c.onBackgroundLight,
                surface = c.surfaceLight,
                onSurface = c.onSurfaceLight,
                surfaceVariant = c.surfaceVariantLight,
                onSurfaceVariant = c.onSurfaceVariantLight,
                outline = c.outlineLight,
                inverseSurface = c.inverseSurfaceLight,
                inverseOnSurface = c.inverseOnSurfaceLight,
                inversePrimary = c.inversePrimaryLight,
            )
        }
    }

    private fun greenDarkScheme(style: ThemeStyle): ColorScheme {
        val c = CapodColorsGreen
        return when (style) {
            ThemeStyle.MEDIUM_CONTRAST -> darkColorScheme(
                primary = c.primaryDarkMediumContrast,
                onPrimary = c.onPrimaryDarkMediumContrast,
                primaryContainer = c.primaryContainerDarkMediumContrast,
                onPrimaryContainer = c.onPrimaryContainerDarkMediumContrast,
                secondary = c.secondaryDarkMediumContrast,
                onSecondary = c.onSecondaryDarkMediumContrast,
                secondaryContainer = c.secondaryContainerDarkMediumContrast,
                onSecondaryContainer = c.onSecondaryContainerDarkMediumContrast,
                tertiary = c.tertiaryDarkMediumContrast,
                onTertiary = c.onTertiaryDarkMediumContrast,
                tertiaryContainer = c.tertiaryContainerDarkMediumContrast,
                onTertiaryContainer = c.onTertiaryContainerDarkMediumContrast,
                error = c.errorDarkMediumContrast,
                onError = c.onErrorDarkMediumContrast,
                errorContainer = c.errorContainerDarkMediumContrast,
                onErrorContainer = c.onErrorContainerDarkMediumContrast,
                background = c.backgroundDarkMediumContrast,
                onBackground = c.onBackgroundDarkMediumContrast,
                surface = c.surfaceDarkMediumContrast,
                onSurface = c.onSurfaceDarkMediumContrast,
                surfaceVariant = c.surfaceVariantDarkMediumContrast,
                onSurfaceVariant = c.onSurfaceVariantDarkMediumContrast,
                outline = c.outlineDarkMediumContrast,
                inverseSurface = c.inverseSurfaceDarkMediumContrast,
                inverseOnSurface = c.inverseOnSurfaceDarkMediumContrast,
                inversePrimary = c.inversePrimaryDarkMediumContrast,
            )
            ThemeStyle.HIGH_CONTRAST -> darkColorScheme(
                primary = c.primaryDarkHighContrast,
                onPrimary = c.onPrimaryDarkHighContrast,
                primaryContainer = c.primaryContainerDarkHighContrast,
                onPrimaryContainer = c.onPrimaryContainerDarkHighContrast,
                secondary = c.secondaryDarkHighContrast,
                onSecondary = c.onSecondaryDarkHighContrast,
                secondaryContainer = c.secondaryContainerDarkHighContrast,
                onSecondaryContainer = c.onSecondaryContainerDarkHighContrast,
                tertiary = c.tertiaryDarkHighContrast,
                onTertiary = c.onTertiaryDarkHighContrast,
                tertiaryContainer = c.tertiaryContainerDarkHighContrast,
                onTertiaryContainer = c.onTertiaryContainerDarkHighContrast,
                error = c.errorDarkHighContrast,
                onError = c.onErrorDarkHighContrast,
                errorContainer = c.errorContainerDarkHighContrast,
                onErrorContainer = c.onErrorContainerDarkHighContrast,
                background = c.backgroundDarkHighContrast,
                onBackground = c.onBackgroundDarkHighContrast,
                surface = c.surfaceDarkHighContrast,
                onSurface = c.onSurfaceDarkHighContrast,
                surfaceVariant = c.surfaceVariantDarkHighContrast,
                onSurfaceVariant = c.onSurfaceVariantDarkHighContrast,
                outline = c.outlineDarkHighContrast,
                inverseSurface = c.inverseSurfaceDarkHighContrast,
                inverseOnSurface = c.inverseOnSurfaceDarkHighContrast,
                inversePrimary = c.inversePrimaryDarkHighContrast,
            )
            else -> darkColorScheme(
                primary = c.primaryDark,
                onPrimary = c.onPrimaryDark,
                primaryContainer = c.primaryContainerDark,
                onPrimaryContainer = c.onPrimaryContainerDark,
                secondary = c.secondaryDark,
                onSecondary = c.onSecondaryDark,
                secondaryContainer = c.secondaryContainerDark,
                onSecondaryContainer = c.onSecondaryContainerDark,
                tertiary = c.tertiaryDark,
                onTertiary = c.onTertiaryDark,
                tertiaryContainer = c.tertiaryContainerDark,
                onTertiaryContainer = c.onTertiaryContainerDark,
                error = c.errorDark,
                onError = c.onErrorDark,
                errorContainer = c.errorContainerDark,
                onErrorContainer = c.onErrorContainerDark,
                background = c.backgroundDark,
                onBackground = c.onBackgroundDark,
                surface = c.surfaceDark,
                onSurface = c.onSurfaceDark,
                surfaceVariant = c.surfaceVariantDark,
                onSurfaceVariant = c.onSurfaceVariantDark,
                outline = c.outlineDark,
                inverseSurface = c.inverseSurfaceDark,
                inverseOnSurface = c.inverseOnSurfaceDark,
                inversePrimary = c.inversePrimaryDark,
            )
        }
    }

    private fun amberLightScheme(style: ThemeStyle): ColorScheme {
        val c = CapodColorsAmber
        return when (style) {
            ThemeStyle.MEDIUM_CONTRAST -> lightColorScheme(
                primary = c.primaryLightMediumContrast,
                onPrimary = c.onPrimaryLightMediumContrast,
                primaryContainer = c.primaryContainerLightMediumContrast,
                onPrimaryContainer = c.onPrimaryContainerLightMediumContrast,
                secondary = c.secondaryLightMediumContrast,
                onSecondary = c.onSecondaryLightMediumContrast,
                secondaryContainer = c.secondaryContainerLightMediumContrast,
                onSecondaryContainer = c.onSecondaryContainerLightMediumContrast,
                tertiary = c.tertiaryLightMediumContrast,
                onTertiary = c.onTertiaryLightMediumContrast,
                tertiaryContainer = c.tertiaryContainerLightMediumContrast,
                onTertiaryContainer = c.onTertiaryContainerLightMediumContrast,
                error = c.errorLightMediumContrast,
                onError = c.onErrorLightMediumContrast,
                errorContainer = c.errorContainerLightMediumContrast,
                onErrorContainer = c.onErrorContainerLightMediumContrast,
                background = c.backgroundLightMediumContrast,
                onBackground = c.onBackgroundLightMediumContrast,
                surface = c.surfaceLightMediumContrast,
                onSurface = c.onSurfaceLightMediumContrast,
                surfaceVariant = c.surfaceVariantLightMediumContrast,
                onSurfaceVariant = c.onSurfaceVariantLightMediumContrast,
                outline = c.outlineLightMediumContrast,
                inverseSurface = c.inverseSurfaceLightMediumContrast,
                inverseOnSurface = c.inverseOnSurfaceLightMediumContrast,
                inversePrimary = c.inversePrimaryLightMediumContrast,
            )
            ThemeStyle.HIGH_CONTRAST -> lightColorScheme(
                primary = c.primaryLightHighContrast,
                onPrimary = c.onPrimaryLightHighContrast,
                primaryContainer = c.primaryContainerLightHighContrast,
                onPrimaryContainer = c.onPrimaryContainerLightHighContrast,
                secondary = c.secondaryLightHighContrast,
                onSecondary = c.onSecondaryLightHighContrast,
                secondaryContainer = c.secondaryContainerLightHighContrast,
                onSecondaryContainer = c.onSecondaryContainerLightHighContrast,
                tertiary = c.tertiaryLightHighContrast,
                onTertiary = c.onTertiaryLightHighContrast,
                tertiaryContainer = c.tertiaryContainerLightHighContrast,
                onTertiaryContainer = c.onTertiaryContainerLightHighContrast,
                error = c.errorLightHighContrast,
                onError = c.onErrorLightHighContrast,
                errorContainer = c.errorContainerLightHighContrast,
                onErrorContainer = c.onErrorContainerLightHighContrast,
                background = c.backgroundLightHighContrast,
                onBackground = c.onBackgroundLightHighContrast,
                surface = c.surfaceLightHighContrast,
                onSurface = c.onSurfaceLightHighContrast,
                surfaceVariant = c.surfaceVariantLightHighContrast,
                onSurfaceVariant = c.onSurfaceVariantLightHighContrast,
                outline = c.outlineLightHighContrast,
                inverseSurface = c.inverseSurfaceLightHighContrast,
                inverseOnSurface = c.inverseOnSurfaceLightHighContrast,
                inversePrimary = c.inversePrimaryLightHighContrast,
            )
            else -> lightColorScheme(
                primary = c.primaryLight,
                onPrimary = c.onPrimaryLight,
                primaryContainer = c.primaryContainerLight,
                onPrimaryContainer = c.onPrimaryContainerLight,
                secondary = c.secondaryLight,
                onSecondary = c.onSecondaryLight,
                secondaryContainer = c.secondaryContainerLight,
                onSecondaryContainer = c.onSecondaryContainerLight,
                tertiary = c.tertiaryLight,
                onTertiary = c.onTertiaryLight,
                tertiaryContainer = c.tertiaryContainerLight,
                onTertiaryContainer = c.onTertiaryContainerLight,
                error = c.errorLight,
                onError = c.onErrorLight,
                errorContainer = c.errorContainerLight,
                onErrorContainer = c.onErrorContainerLight,
                background = c.backgroundLight,
                onBackground = c.onBackgroundLight,
                surface = c.surfaceLight,
                onSurface = c.onSurfaceLight,
                surfaceVariant = c.surfaceVariantLight,
                onSurfaceVariant = c.onSurfaceVariantLight,
                outline = c.outlineLight,
                inverseSurface = c.inverseSurfaceLight,
                inverseOnSurface = c.inverseOnSurfaceLight,
                inversePrimary = c.inversePrimaryLight,
            )
        }
    }

    private fun amberDarkScheme(style: ThemeStyle): ColorScheme {
        val c = CapodColorsAmber
        return when (style) {
            ThemeStyle.MEDIUM_CONTRAST -> darkColorScheme(
                primary = c.primaryDarkMediumContrast,
                onPrimary = c.onPrimaryDarkMediumContrast,
                primaryContainer = c.primaryContainerDarkMediumContrast,
                onPrimaryContainer = c.onPrimaryContainerDarkMediumContrast,
                secondary = c.secondaryDarkMediumContrast,
                onSecondary = c.onSecondaryDarkMediumContrast,
                secondaryContainer = c.secondaryContainerDarkMediumContrast,
                onSecondaryContainer = c.onSecondaryContainerDarkMediumContrast,
                tertiary = c.tertiaryDarkMediumContrast,
                onTertiary = c.onTertiaryDarkMediumContrast,
                tertiaryContainer = c.tertiaryContainerDarkMediumContrast,
                onTertiaryContainer = c.onTertiaryContainerDarkMediumContrast,
                error = c.errorDarkMediumContrast,
                onError = c.onErrorDarkMediumContrast,
                errorContainer = c.errorContainerDarkMediumContrast,
                onErrorContainer = c.onErrorContainerDarkMediumContrast,
                background = c.backgroundDarkMediumContrast,
                onBackground = c.onBackgroundDarkMediumContrast,
                surface = c.surfaceDarkMediumContrast,
                onSurface = c.onSurfaceDarkMediumContrast,
                surfaceVariant = c.surfaceVariantDarkMediumContrast,
                onSurfaceVariant = c.onSurfaceVariantDarkMediumContrast,
                outline = c.outlineDarkMediumContrast,
                inverseSurface = c.inverseSurfaceDarkMediumContrast,
                inverseOnSurface = c.inverseOnSurfaceDarkMediumContrast,
                inversePrimary = c.inversePrimaryDarkMediumContrast,
            )
            ThemeStyle.HIGH_CONTRAST -> darkColorScheme(
                primary = c.primaryDarkHighContrast,
                onPrimary = c.onPrimaryDarkHighContrast,
                primaryContainer = c.primaryContainerDarkHighContrast,
                onPrimaryContainer = c.onPrimaryContainerDarkHighContrast,
                secondary = c.secondaryDarkHighContrast,
                onSecondary = c.onSecondaryDarkHighContrast,
                secondaryContainer = c.secondaryContainerDarkHighContrast,
                onSecondaryContainer = c.onSecondaryContainerDarkHighContrast,
                tertiary = c.tertiaryDarkHighContrast,
                onTertiary = c.onTertiaryDarkHighContrast,
                tertiaryContainer = c.tertiaryContainerDarkHighContrast,
                onTertiaryContainer = c.onTertiaryContainerDarkHighContrast,
                error = c.errorDarkHighContrast,
                onError = c.onErrorDarkHighContrast,
                errorContainer = c.errorContainerDarkHighContrast,
                onErrorContainer = c.onErrorContainerDarkHighContrast,
                background = c.backgroundDarkHighContrast,
                onBackground = c.onBackgroundDarkHighContrast,
                surface = c.surfaceDarkHighContrast,
                onSurface = c.onSurfaceDarkHighContrast,
                surfaceVariant = c.surfaceVariantDarkHighContrast,
                onSurfaceVariant = c.onSurfaceVariantDarkHighContrast,
                outline = c.outlineDarkHighContrast,
                inverseSurface = c.inverseSurfaceDarkHighContrast,
                inverseOnSurface = c.inverseOnSurfaceDarkHighContrast,
                inversePrimary = c.inversePrimaryDarkHighContrast,
            )
            else -> darkColorScheme(
                primary = c.primaryDark,
                onPrimary = c.onPrimaryDark,
                primaryContainer = c.primaryContainerDark,
                onPrimaryContainer = c.onPrimaryContainerDark,
                secondary = c.secondaryDark,
                onSecondary = c.onSecondaryDark,
                secondaryContainer = c.secondaryContainerDark,
                onSecondaryContainer = c.onSecondaryContainerDark,
                tertiary = c.tertiaryDark,
                onTertiary = c.onTertiaryDark,
                tertiaryContainer = c.tertiaryContainerDark,
                onTertiaryContainer = c.onTertiaryContainerDark,
                error = c.errorDark,
                onError = c.onErrorDark,
                errorContainer = c.errorContainerDark,
                onErrorContainer = c.onErrorContainerDark,
                background = c.backgroundDark,
                onBackground = c.onBackgroundDark,
                surface = c.surfaceDark,
                onSurface = c.onSurfaceDark,
                surfaceVariant = c.surfaceVariantDark,
                onSurfaceVariant = c.onSurfaceVariantDark,
                outline = c.outlineDark,
                inverseSurface = c.inverseSurfaceDark,
                inverseOnSurface = c.inverseOnSurfaceDark,
                inversePrimary = c.inversePrimaryDark,
            )
        }
    }
}
